import type { DashboardData } from "@/lib/types";

const rows = [
  { id: 1, indicator: "Indeks Kepuasan Layanan", category: "Layanan Publik", region: "Semua Wilayah", period: "Tahunan", year: 2025, value: 88.6, unit: "skor", source: "Survei Layanan Publik" },
  { id: 2, indicator: "Cakupan Layanan Kesehatan", category: "Kesehatan", region: "Kota Utama", period: "Tahunan", year: 2025, value: 94.2, unit: "persen", source: "Dinas Kesehatan" },
  { id: 3, indicator: "Partisipasi Pendidikan", category: "Pendidikan", region: "Wilayah Barat", period: "Tahunan", year: 2025, value: 91.7, unit: "persen", source: "Dinas Pendidikan" },
  { id: 4, indicator: "Pertumbuhan UMKM Terdata", category: "Ekonomi", region: "Wilayah Timur", period: "Tahunan", year: 2025, value: 12.4, unit: "persen", source: "Dinas Koperasi dan UMKM" },
  { id: 5, indicator: "Respon Pengaduan Tepat Waktu", category: "Layanan Publik", region: "Kota Utama", period: "Triwulan", year: 2024, value: 82.1, unit: "persen", source: "Unit Layanan Informasi" },
  { id: 6, indicator: "Akses Sanitasi Layak", category: "Kesehatan", region: "Wilayah Barat", period: "Tahunan", year: 2024, value: 89.5, unit: "persen", source: "Dinas Kesehatan" },
  { id: 7, indicator: "Sekolah Terakreditasi", category: "Pendidikan", region: "Semua Wilayah", period: "Semester", year: 2024, value: 86.8, unit: "persen", source: "Dinas Pendidikan" },
  { id: 8, indicator: "Investasi Daerah", category: "Ekonomi", region: "Kota Utama", period: "Tahunan", year: 2024, value: 74.3, unit: "miliar", source: "Dinas Penanaman Modal" },
  { id: 9, indicator: "Kunjungan Portal Informasi", category: "Layanan Publik", region: "Semua Wilayah", period: "Bulanan", year: 2023, value: 128.4, unit: "ribu", source: "Analytics Website" },
  { id: 10, indicator: "Ketersediaan Tenaga Medis", category: "Kesehatan", region: "Wilayah Timur", period: "Tahunan", year: 2023, value: 76.9, unit: "persen", source: "Dinas Kesehatan" },
  { id: 11, indicator: "Literasi Digital Sekolah", category: "Pendidikan", region: "Kota Utama", period: "Tahunan", year: 2023, value: 80.2, unit: "persen", source: "Dinas Pendidikan" },
  { id: 12, indicator: "Koperasi Aktif", category: "Ekonomi", region: "Wilayah Barat", period: "Tahunan", year: 2023, value: 68.7, unit: "persen", source: "Dinas Koperasi dan UMKM" },
  { id: 13, indicator: "Indeks Kepuasan Layanan", category: "Layanan Publik", region: "Semua Wilayah", period: "Tahunan", year: 2022, value: 79.4, unit: "skor", source: "Survei Layanan Publik" },
  { id: 14, indicator: "Cakupan Layanan Kesehatan", category: "Kesehatan", region: "Kota Utama", period: "Tahunan", year: 2022, value: 84.9, unit: "persen", source: "Dinas Kesehatan" },
  { id: 15, indicator: "Partisipasi Pendidikan", category: "Pendidikan", region: "Wilayah Timur", period: "Tahunan", year: 2022, value: 83.6, unit: "persen", source: "Dinas Pendidikan" },
  { id: 16, indicator: "Pertumbuhan UMKM Terdata", category: "Ekonomi", region: "Semua Wilayah", period: "Tahunan", year: 2022, value: 8.9, unit: "persen", source: "Dinas Koperasi dan UMKM" },
];

export async function getDashboardData(): Promise<DashboardData> {
  return {
    indicators: [
      {
        id: 1,
        name: "Indeks Kepuasan Layanan",
        description: "Skor kepuasan masyarakat terhadap layanan prioritas instansi.",
        category: "Layanan Publik",
        unit: "skor",
        source: "Survei Layanan Publik",
        year: 2025,
        value: 88.6,
        trend: 7.9,
        status: "aktif",
      },
      {
        id: 2,
        name: "Cakupan Layanan Kesehatan",
        description: "Persentase masyarakat yang mendapat akses layanan kesehatan dasar.",
        category: "Kesehatan",
        unit: "persen",
        source: "Dinas Kesehatan",
        year: 2025,
        value: 94.2,
        trend: 5.2,
        status: "aktif",
      },
      {
        id: 3,
        name: "Partisipasi Pendidikan",
        description: "Tingkat partisipasi pendidikan pada kelompok usia sekolah.",
        category: "Pendidikan",
        unit: "persen",
        source: "Dinas Pendidikan",
        year: 2025,
        value: 91.7,
        trend: 4.9,
        status: "aktif",
      },
      {
        id: 4,
        name: "Pertumbuhan UMKM Terdata",
        description: "Perubahan jumlah UMKM aktif yang masuk basis data instansi.",
        category: "Ekonomi",
        unit: "persen",
        source: "Dinas Koperasi dan UMKM",
        year: 2025,
        value: 12.4,
        trend: 3.5,
        status: "perlu-validasi",
      },
    ],
    rows,
    chartSeries: [
      { year: 2022, Kesehatan: 84.9, Pendidikan: 83.6, Ekonomi: 8.9, "Layanan Publik": 79.4 },
      { year: 2023, Kesehatan: 76.9, Pendidikan: 80.2, Ekonomi: 68.7, "Layanan Publik": 128.4 },
      { year: 2024, Kesehatan: 89.5, Pendidikan: 86.8, Ekonomi: 74.3, "Layanan Publik": 82.1 },
      { year: 2025, Kesehatan: 94.2, Pendidikan: 91.7, Ekonomi: 12.4, "Layanan Publik": 88.6 },
    ],
    publications: [
      {
        id: 1,
        title: "Laporan Kinerja Tahunan 2025",
        description: "Ringkasan capaian indikator strategis, evaluasi program, dan tindak lanjut layanan publik.",
        date: "12 Mei 2026",
        category: "Laporan Tahunan",
        fileLabel: "PDF",
      },
      {
        id: 2,
        title: "Statistik Sektoral Prioritas",
        description: "Kompilasi data sektoral untuk kebutuhan analisis, koordinasi, dan keterbukaan informasi.",
        date: "29 April 2026",
        category: "Statistik",
        fileLabel: "XLSX",
      },
      {
        id: 3,
        title: "Infografis Layanan Informasi",
        description: "Materi publikasi visual terkait alur layanan, kanal pengaduan, dan standar pelayanan.",
        date: "18 April 2026",
        category: "Infografis",
        fileLabel: "PNG",
      },
    ],
    activities: [
      {
        id: 1,
        title: "Forum Validasi Data Strategis",
        caption: "Koordinasi lintas unit untuk memastikan data dashboard lebih akurat dan mudah dipahami publik.",
        imageUrl: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=80",
      },
      {
        id: 2,
        title: "Pelayanan Terpadu Masyarakat",
        caption: "Dokumentasi layanan lapangan, kanal informasi, dan konsultasi data untuk masyarakat umum.",
        imageUrl: "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=80",
      },
      {
        id: 3,
        title: "Rapat Monitoring Pimpinan",
        caption: "Pemantauan ringkasan indikator prioritas sebagai bahan pengambilan keputusan.",
        imageUrl: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1200&q=80",
      },
    ],
    videos: [
      {
        id: 1,
        title: "Profil Dashboard Digital",
        description: "Video pengantar tentang pemanfaatan data strategis untuk transparansi informasi publik.",
        embedUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      },
    ],
    contact: {
      institution: "Instansi Pemerintah Daerah",
      address: "Jl. Merdeka No. 10, Pusat Pemerintahan, Indonesia",
      phone: "(021) 1234 5678",
      whatsapp: "+62 812 3456 7890",
      email: "layanan@instansi.go.id",
      instagram: "@instansi.resmi",
      youtube: "Instansi Resmi",
      website: "www.instansi.go.id",
      mapEmbedUrl: "https://www.google.com/maps?q=Jakarta%20City%20Hall&output=embed",
    },
    filters: {
      years: ["Semua Tahun", "2025", "2024", "2023", "2022"],
      categories: ["Semua Kategori", "Kesehatan", "Pendidikan", "Ekonomi", "Layanan Publik"],
      regions: ["Semua Wilayah", "Kota Utama", "Wilayah Barat", "Wilayah Timur"],
    },
  };
}
